MKDIR E:\asdsadsadsad
MKDIR E:\asdsadsadsad\BACKUP
EXP MAINTENANCE_MANAGEMENT/MMDB owner=MAINTENANCE_MANAGEMENT file=E:\asdsadsadsad\BACKUP\MAINTENANCE_MANAGEMENT-20-Mar-23~06-43PM.DMP Log=Backup.log;
EXIT
